trigger:
  branches:
    include: [main]
  paths:
    include: [infrastructure/terraform/*]

variables:
- group: StayHere-Variables

stages:
- stage: TerraformPlan
  jobs:
  - job: Plan
    pool: { vmImage: 'ubuntu-latest' }
    steps:
    - task: TerraformInstaller@1
      displayName: 'Install Latest Terraform'
      inputs:
        terraformVersion: 'latest'

    - task: TerraformTask@5
      displayName: 'Terraform Init'
      inputs:
        provider: 'azurerm'
        command: 'init'
        backendServiceArm: 'Azure-StayHere-Conn'
        backendAzureRmResourceGroupName: 'rg-terraform-mgmt'
        backendAzureRmStorageAccountName: 'ststayheretfstate'
        backendAzureRmContainerName: 'tfstate'
        backendAzureRmKey: 'terraform.tfstate'

    - task: TerraformTask@5
      name: terraformPlan
      displayName: 'Terraform Plan'
      inputs:
        provider: 'azurerm'
        command: 'plan'
        commandOptions: '-out tfplan'
        environmentServiceNameAzureRM: 'Azure-StayHere-Conn'

- stage: TerraformApply
  dependsOn: TerraformPlan
  condition: and(succeeded('TerraformPlan'), eq(dependencies.TerraformPlan.outputs['Plan.terraformPlan.changesPresent'], 'true'))
  jobs:
  - deployment: Apply
    pool: { vmImage: 'ubuntu-latest' }
    environment: 'production'
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self

          - task: TerraformInstaller@1
            displayName: 'Install Latest Terraform'
            inputs:
              terraformVersion: 'latest'

          - task: TerraformTask@5
            displayName: 'Terraform Init'
            inputs:
              provider: 'azurerm'
              command: 'init'
              backendServiceArm: 'Azure-StayHere-Conn'
              backendAzureRmResourceGroupName: 'rg-terraform-mgmt'
              backendAzureRmStorageAccountName: 'ststayheretfstate'
              backendAzureRmContainerName: 'tfstate'
              backendAzureRmKey: 'terraform.tfstate'

          - task: TerraformTask@5
            displayName: 'Terraform Apply'
            inputs:
              provider: 'azurerm'
              command: 'apply'
              commandOptions: 'tfplan'
              environmentServiceNameAzureRM: 'Azure-StayHere-Conn'