using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace StayHere.Infrastructure.Persistence.Migrations
{
    /// <inheritdoc />
    public partial class UpdateEmbeddingDimension : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // Clear existing embeddings — they were generated by a different model and are incompatible
            migrationBuilder.Sql("UPDATE listings SET embedding = NULL;");
            // Resize column from vector(1536) to vector(768) to match text-embedding-004 output
            migrationBuilder.Sql("ALTER TABLE listings ALTER COLUMN embedding TYPE vector(768);");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("UPDATE listings SET embedding = NULL;");
            migrationBuilder.Sql("ALTER TABLE listings ALTER COLUMN embedding TYPE vector(1536);");
        }
    }
}
